project_id = "uasluhbtcpuigwkuslum"

[auth.external.spotify]
enabled = true
client_id = ""
secret = ""
redirect_uri = ""

[functions.get-location]
verify_jwt = false

[functions.process-document]
verify_jwt = false